# Exception Handling

# try:block lets you test a code
# except: error is handled here
# else:
# finally: executes the code no matter what
try:
    print(a)
except:
    print("not defined")